### ISSUE TITLE
cutoff width config isn't enough to determine HiDPI

### ISSUE THREAD

**Issue by vito** [mcanders/atom-hidpi#1]
I have a HiDPI laptop whose native resolution is 2560x1700, and is normally set to 1280x850. I also have a 27" monitor whose resolution is 2560x1440.

There isn't a way to configure this package such that it scales only on my actual HiDPI display (the laptop); if I set it to 2560 (or the default 2300) it scales to 2x also on my 1440p display, since they're the same width.

Is there any way to access the system's current resolution setting, vs. the native resolution? If so, I wonder if this plugin could just sort of "auto-configure" based on the ratio between the two (native resolution / resolution setting >= 2). Or at least provide a second field.

Otherwise, very useful plugin - thanks for publishing it!

**Comment by cart** [comment]
For the issue of large monitors with large resolutions I don't think there is a reliable way to detect their DPI.  The best fix I can think of is to take an optional list of resolutions and manual scaling settings for them.  But this won't help if two monitors have the same resolution.

I should provide a cutoff height option as well.  This should fix your problem and make the addon work for vertical monitors.

I don't think atom/chrome provides the native resolution.  Even if it did I'm not sure your ratio idea would be a good general fix because it is specific to your monitor setup/configuration and intent.

**Comment by vito** [comment]
Ahh, I'm using [Crouton](https://github.com/dnschneid/crouton) which may be confusing things. In Atom, `screen` in the console reports the native resolution of whatever the Crouton window size is, probably because of how Crouton happens to implement HiDPI, and with X11 in its own arbitrarily-sized window.

Which also means the cutoff size only triggers if I have the Crouton window full-screen/maximized, which I usually do anyway.

Detecting all that may not possible with an Atom package though. Being able to specify a cutoff height would work for me. Thanks!

**Comment by cart** [comment]
3632e0fd932e278ad4f2458e6e3ff41f357109ab fixes this issue by adding "Cutoff Height" and "Manual Resolution Scale Factors"
